# Generated by Django 5.0.6 on 2024-06-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_question_answer_mode_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used_in_exam',
            field=models.BooleanField(default=False),
        ),
    ]
