# Generated by Django 5.0.6 on 2024-06-25 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_question_used_in_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.fileupload'),
        ),
    ]
